# Generated by Django 5.1.2 on 2024-10-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
